name: 'media_template'
version: '0.0.4'
config-version: 2

require-dbt-version: [">=0.19.0", "<0.20.0"]

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

vars:
  facebook_ads_ids: []
  facebook_organic_ids: []
  google_ads_ids: []
  google_ads_conversions_enabled: false
  google_analytics_ids: []
  google_campaign_manager_ids: []
  google_campaign_manager_conversions_enabled: false
  instagram_organic_ids: []
  linkedin_ads_ids: []
  linkedin_ads_conversions_enabled: false
  linkedin_organic_ids: []
  pinterest_ads_ids: []
  twitter_ads_ids: []
  twitter_ads_conversions_enabled: false
  twitter_organic_ids: []
  youtube_organic_ids: []

models:
  media_template:
    +persist_docs:
      relation: true
      columns: true
    
    rollups:
      display:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging
      search_paid:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging
      social_organic:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging
      social_paid:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging
      summary:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging

    
    facebook_ads:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging
    
    facebook_organic:
      staging:
        +schema: staging
    
    google_ads:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging

    google_analytics:
      marts:
        +materialized: table
      staging:
        +schema: staging

    google_campaign_manager:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging
    
    instagram_organic:
      staging:
        +schema: staging
    
    linkedin_ads:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging

    linkedin_organic:
      staging:
        +schema: staging
    
    pinterest_ads:
      marts:
        +materialized: table
      staging:
        +schema: staging
    
    twitter_ads:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging

    twitter_organic:
      staging:
        +schema: staging

    youtube_organic:
      marts:
        +materialized: table
      staging:
        +schema: staging