name: 'media_template'
version: '0.0.4'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  media_template:
    +persist_docs:
      relation: true
      columns: true
    
    rollups:
      display:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging
      search_paid:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging
      social_organic:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging
      social_paid:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging
      summary:
        +materialized: table
        intermediate:
          +materialized: view
          +schema: staging

    
    facebook_ads:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging
    
    facebook_organic:
      staging:
        +schema: staging
    
    google_ads:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging

    google_analytics:
      marts:
        +materialized: table
      staging:
        +schema: staging

    google_campaign_manager:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging
    
    instagram_organic:
      staging:
        +schema: staging
    
    linkedin_ads:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging

    linkedin_organic:
      staging:
        +schema: staging
    
    pinterest_ads:
      marts:
        +materialized: table
      staging:
        +schema: staging
    
    twitter_ads:
      marts:
        +materialized: table
      intermediate:
        +schema: staging
      staging:
        +schema: staging

    twitter_organic:
      staging:
        +schema: staging

    youtube_organic:
      marts:
        +materialized: table
      staging:
        +schema: staging