name: 'media_template'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=0.17.1"]

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

vars:
  client_name: 'demo_client'
  google_analytics_ids: []
  google_ads_ids: ['9381907822', '3742196383', '7924374334', '8584468339']
  google_campaign_manager_ids: ['4816067', '5165559', '4796962', '9412988']
  facebook_ads_ids: ['act_10153307131161289', 'act_10153216470876289', 'act_10153651985701289', 'act_10153313311861289', 'act_1151624751539530']
  linkedin_ads_ids: ['506578922']
  twitter_ads_ids: []
  pinterest_ads_ids: ['549760653624', '549759455869', '549760732021']
  facebook_organic_ids: []
  instagram_organic_ids: []
  linkedin_organic_ids: []
  twitter_organic_ids: []
  pinterest_organic_ids: []
  youtube_organic_ids: []

models:
  media_template:
    +persist_docs:
      relation: true
      columns: true
    
    marts:
      +materialized: table

      display:
        intermediate:
          +materialized: view
          +schema: staging
        google_campaign_manager:
          intermediate:
            +materialized: view
            +schema: staging
            
      search_paid:
        intermediate:
          +materialized: view
          +schema: staging
        google_ads:
          intermediate:
            +materialized: view
            +schema: staging

      social_organic:
        intermediate:
          +materialized: view
          +schema: staging

      social_paid:
        intermediate:
          +materialized: view
          +schema: staging
        facebook_ads:
          intermediate:
            +materialized: view
            +schema: staging
        linkedin_ads:
          intermediate:
            +materialized: view
            +schema: staging
          
      summary:
        intermediate:
          +materialized: view
          +schema: staging

    staging:
      +materialized: view
      +schema: staging